@require
  jquery:     '1.7.X'
  backbone:   '0.9.X'
  underscore: '1.3.X'
  
  $vendordir: 'deps'

@bundler 
  js: ['test'], 
  compress: true, 
  output: 'build'

@coffeescript "coffee", output: "js"
@ics          "iced",   output: "js/iced"