javascript "script1", ->
  @options
    build: "./js/build"
    compress: true
  
  @bundles 'test'
  @coffeescript "./coffee", output: "./js"

javascript "script2", ->
  @options
    type: "js"
    build: "./js/build"
    compress: true
  
  @bundles 'test2'
  @coffeescript "./coffee", output: "./js"
  @source "./deps", follow: false
