@require
  nib: '0.3.X'
  test: '0.1.1'

@bundler
  css: ['testcss1', 'testless1', 'test1', 'test2']
  compress: true
  output: 'css/build'

@css    'css'
@less   'less'
@less   'less/auto', output: 'css/build-less'
@stylus 'stylus'
@stylus 'stylus-nib'
