require {nib: '0.3.X'}
require './test'

bundler 'css/build', {
  css: ['testcss1', 'testless1', 'test1', 'test2']
  compress: true
}

css    'css'

less   'less'
less   'less/auto', {output: 'css/build-less'}

stylus 'stylus'
stylus 'stylus-nib'