stylesheets "styles1",
  build: "./css/build-less"
  bundles: ["testcss1", "testless1"]
  compress: true
  
  ->
    @source "./css"
    @less "./less"
    @less "./less/auto", 
      compileAll: true

css "styles2", ->
  @options
    build: "./css/build-stylus"
    bundles: ["test1", "test2"]
    compress: true
  
  @stylus "./stylus"
  @stylus "./stylus-nib",
    modules: "nib"
